codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
ignore:
  - conftest.py
  - "**/conftest.py"
  - "**tests**/test_*.py"
  - "database/tests/factories/**"
comment:
  show_critical_paths: true
  layout: "reach,diff,flags,tree,betaprofiling"
