http:
    force_https: yes
    cookie_secret: Z1353^dggqdbc,kp0)661
    timeouts:
      connect: 10
      receive: 15
  cache:
    yaml: 600  # 10 minutes
    tree: 600  # 10 minutes
    diff: 300  # 5 minutes
    chunks: 300  # 5 minutes
    uploads: 86400  # 1 day

services:
  redis_url: redis://redis:@localhost:6379/
  minio:
    hash_key: 88f572f4726e4971827415efa8867978  # never change this
    bucket: codecov
    periodic_callback_ms: false
    verify_ssl: false
