version: "3"

services:
  api:
    image: codecov/api:latest
    networks:
      - codecovapi
    ports:
      - "5100:8000"
    labels:
      - "traefik.tags=api"
      - "traefik.backend=api"
      - "traefik.port=5100"
    depends_on:
      - postgres
      - redis
    entrypoint:
      - ./api.sh
    volumes:
      - ./:/app
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,api.localhost
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - codecovapi
    ports:
      - "5432:5432"
  redis:
    image: redis:4.0-alpine
    volumes:
      - redis-volume:/data
    networks:
      - codecovapi
  worker-new:
    image: codecov/worker
    build: ./worker
    working_dir: /app/
    entrypoint: sh worker.sh
    volumes:
      - ./worker:/app/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - codecovapi
    depends_on:
      - redis

volumes:
  postgres-volume:
  redis-volume:

networks:
  codecovapi:
    driver: bridge
