version: "3"

services:
  api:
    image: codecov/enterprise-api:v4.6.2
    networks:
      - codecovapi
    ports:
      - "5100:8000"
    labels:
      - "traefik.tags=api"
      - "traefik.backend=api"
      - "traefik.port=5100"
    depends_on:
      - postgres
      - redis
#    entrypoint:
#      - ./api
    volumes:
      - ./:/app
    environment:
      - RUN_ENV=DEV
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - codecovapi
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:4.0-alpine
    volumes:
      - redis-volume:/data
    networks:
      - codecovapi

volumes:
  postgres-volume:
  redis-volume:

networks:
  codecovapi:
    driver: bridge
